export const FETCH_RENTALS = 'FETCH_RENTALS';
export const FETCH_RENTALS_BY_ID = 'FETCH_RENTALS_BY_ID';
export const FETCH_RENTALS_BY_ID_INIT = 'FETCH_RENTALS_BY_ID_INIT';

export const FETCH_RENTALS_INIT = 'FETCH_RENTALS_INIT';
export const FETCH_RENTALS_FAIL = 'FETCH_RENTALS_FAIL';

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";