export const FETCH_RENTALS = 'FETCH_RENTALS';
export const FETCH_RENTALS_BY_ID = 'FETCH_RENTALS_BY_ID';

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";